package Day1;

public class Task6 {
/**
 * Обьявите переменную int с именем k. Присвойте ей любое значение от 1 до 9. Используя любой цикл (for while)
 * выведите в консоль таблицу умножения для этой цифры
 * Output:
 * 1 x k =...
 * 2 x k =...
 * 3 x k =...
 * 4 x k =...
 * 5 x k =...
 * 6 x k =...
 * 7 x k =...
 * 8 x k =...
 * 9 x k =...
 */
public static void main(String[] args) {
    int k = 6;
    for(int i=1;i<10;i++){
        System.out.println(i+" x "+k+" = "+i*k);
    }
}
}
